-- Create ingests table
CREATE TABLE ingests(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
		CONSTRAINT c_id
			CHECK (id >= 1 AND id <= 9007199254740991),
	process SMALLINT
		CONSTRAINT c_process
			NOT NULL
			CHECK (process IN (0, 1))
			DEFAULT 0,
	visibility SMALLINT
		CONSTRAINT c_visibility
			NOT NULL
			CHECK (visibility IN (0, 1))
			DEFAULT 0,
	relative_path VARCHAR
		CONSTRAINT c_relative_path
			NOT NULL
			CHECK (length(relative_path) >= 4 AND relative_path !~ '^/'),
	fingerprint VARCHAR(64) NOT NULL,
	ingested_at TIMESTAMP NOT NULL,
	captured_at TIMESTAMP
		CONSTRAINT c_captured_at
			NOT NULL
			CHECK (captured_at <= ingested_at),
	updated_at TIMESTAMP
		CONSTRAINT c_updated_at
			NOT NULL
			CHECK (updated_at >= ingested_at),
	executions JSONB
		CONSTRAINT c_executions
			NOT NULL
			CHECK (jsonb_typeof(executions) = 'array')
			DEFAULT '[]'::jsonb,
	UNIQUE (fingerprint)
);

-- Create images table
CREATE TABLE images(
	ingest_id BIGINT
		CONSTRAINT c_images_ingest_id
			PRIMARY KEY
			REFERENCES ingests(id),
	ingested_at TIMESTAMP NOT NULL,
	kind SMALLINT
		CONSTRAINT c_kind
			NOT NULL
			CHECK (kind IN (0, 1, 2, 3))
			DEFAULT 0,
	original JSONB
		CONSTRAINT c_original
			NOT NULL
			CHECK (jsonb_typeof(original) = 'object'),
	fallback JSONB
		CONSTRAINT c_fallback
			CHECK (jsonb_typeof(fallback) = 'object'),
	variants JSONB
		CONSTRAINT c_variants
			NOT NULL
			CHECK (jsonb_typeof(variants) = 'array')
);

-- Create stats table
CREATE TABLE stats(
	ingest_id BIGINT
		CONSTRAINT c_stats_ingest_id
			PRIMARY KEY
			REFERENCES ingests(id),
	score SMALLINT NOT NULL,
	score_evaluated SMALLINT NOT NULL,
	score_evaluated_at TIMESTAMP,
	first_loved_at TIMESTAMP,
	last_loved_at TIMESTAMP,
	hall_of_fame_at TIMESTAMP,
	last_viewed_at TIMESTAMP
		CONSTRAINT c_last_viewed_at
			CHECK (
				(view_count <> 0::BIGINT AND last_viewed_at IS NOT NULL)
				OR
				(view_count = 0::BIGINT AND last_viewed_at IS NULL)
			),
	view_count BIGINT
		CONSTRAINT c_view_count
			NOT NULL
			CHECK (view_count >= 0)
			DEFAULT 0,
	view_milestone_count BIGINT
		CONSTRAINT c_view_milestone_count
			NOT NULL
			CHECK (view_milestone_count >= 0 AND view_milestone_count <= view_count)
			DEFAULT 0,
	view_milestone_archived_at TIMESTAMP
		CONSTRAINT c_view_milestone_archived_at
			CHECK (
				(view_milestone_count <> 0::BIGINT AND view_milestone_archived_at IS NOT NULL)
				OR
				(view_milestone_count = 0::BIGINT AND view_milestone_archived_at IS NULL)
			),
	CONSTRAINT c_loved_at_pair
		CHECK (
			(first_loved_at IS NULL AND last_loved_at IS NULL)
			OR
			(first_loved_at IS NOT NULL AND last_loved_at IS NOT NULL)
		),
	CONSTRAINT c_loved_at_order
		CHECK (first_loved_at IS NULL OR first_loved_at <= last_loved_at)
);

-- Create users table
CREATE TABLE users (
	id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	daily_love_used SMALLINT
		CONSTRAINT c_daily_love_used
			NOT NULL
			CHECK (daily_love_used >= 0 AND daily_love_used <= 32767)
			DEFAULT 0
);
INSERT INTO users(id) VALUES(1);
