package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"unicode"
)

type sqlDialect string

const (
	dialectMySQL    sqlDialect = "mysql"
	dialectPostgres sqlDialect = "postgres"
	dialectSQLite   sqlDialect = "sqlite"
)

const (
	stateNormal = iota
	stateString
	stateIdentifier
	stateLineComment
	stateBlockComment
	stateDollarQuote
)

var operatorPattern = regexp.MustCompile(
	`\s*(::|->>|->|#>>|#>|@>|<@|=|!=|<>|<=|>=|<|>|\(|\)|,|;)\s*`,
)

func isAllowedDollarTagChar(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_'
}

func readDollarQuoteDelimiter(input []byte, start int) ([]byte, bool) {
	if start >= len(input) || input[start] != '$' {
		return nil, false
	}

	i := start + 1
	for i < len(input) && isAllowedDollarTagChar(input[i]) {
		i++
	}
	if i >= len(input) || input[i] != '$' {
		return nil, false
	}
	return input[start : i+1], true
}

func minifySQL(input []byte, dialect sqlDialect) []byte {
	var output strings.Builder

	state := stateNormal
	space_pending := false
	var identifierQuote byte
	var dollarDelimiter []byte

	for i := 0; i < len(input); i++ {
		c := input[i]

		switch state {
		case stateNormal:
			if dialect == dialectPostgres && c == '$' {
				if delimiter, ok := readDollarQuoteDelimiter(input, i); ok {
					dollarDelimiter = delimiter
					state = stateDollarQuote
					output.Write(delimiter)
					i += len(delimiter) - 1
					continue
				}
			}

			if c == '\'' {
				state = stateString
				output.WriteByte(c)
				continue
			}

			if c == '"' || c == '`' {
				state = stateIdentifier
				identifierQuote = c
				output.WriteByte(c)
				continue
			}

			if c == '-' && i+1 < len(input) && input[i+1] == '-' {
				state = stateLineComment
				i++
				continue
			}

			if c == '/' && i+1 < len(input) && input[i+1] == '*' {
				state = stateBlockComment
				i++
				continue
			}

			if unicode.IsSpace(rune(c)) {
				space_pending = true
				continue
			}

			if space_pending {
				output.WriteByte(' ')
				space_pending = false
			}

			output.WriteByte(c)

		case stateString:
			output.WriteByte(c)

			if c == '\'' {
				if dialect == dialectMySQL {
					backslashCount := 0
					for j := i - 1; j >= 0 && input[j] == '\\'; j-- {
						backslashCount++
					}
					if backslashCount%2 == 1 {
						continue
					}
				}

				if i+1 < len(input) && input[i+1] == '\'' {
					output.WriteByte(input[i+1])
					i++
					continue
				}
				state = stateNormal
			}

		case stateIdentifier:
			output.WriteByte(c)

			if c == identifierQuote {
				if i+1 < len(input) && input[i+1] == identifierQuote {
					output.WriteByte(input[i+1])
					i++
					continue
				}
				state = stateNormal
				identifierQuote = 0
			}

		case stateLineComment:
			if c == '\n' {
				state = stateNormal
			}

		case stateBlockComment:
			if c == '*' && i+1 < len(input) && input[i+1] == '/' {
				state = stateNormal
				i++
			}

		case stateDollarQuote:
			if c == '$' && len(dollarDelimiter) > 0 && bytes.HasPrefix(input[i:], dollarDelimiter) {
				output.Write(dollarDelimiter)
				i += len(dollarDelimiter) - 1
				state = stateNormal
				dollarDelimiter = nil
				continue
			}
			output.WriteByte(c)
		}
	}

	s := output.String()

	// NOTE: operatorPattern runs on the full SQL text. It can affect quoted
	// strings/identifiers. We keep it for now but avoid using it to rewrite
	// content-sensitive migrations.
	s = operatorPattern.ReplaceAllString(s, "$1")

	return []byte(strings.TrimSpace(s))
}

func processSQLFile(
	input_file string,
	output_file string,
	dialect sqlDialect,
) error {
	data, err := os.ReadFile(input_file)
	if err != nil {
		return err
	}

	minified := minifySQL(data, dialect)
	return os.WriteFile(output_file, minified, 0644)
}

func addCommentAndStripGenerate(src []byte) []byte {
	lines := bytes.Split(src, []byte{'\n'})

	out := make([][]byte, 0, len(lines))
	out = append(out, []byte("// Code generated by sql_minify. DO NOT EDIT.\n"))

	for _, line := range lines {
		trim := bytes.TrimSpace(line)

		if bytes.HasPrefix(trim, []byte("//go:generate")) {
			continue
		}

		out = append(out, line)
	}

	return bytes.Join(out, []byte{'\n'})
}

func processGoFile(input_file string, output_file string) error {
	data, err := os.ReadFile(input_file)
	if err != nil {
		return err
	}

	noGenerated := addCommentAndStripGenerate(data)
	return os.WriteFile(output_file, noGenerated, 0644)
}

func processDirectory(input_dir string, output_dir string, dialect sqlDialect) error {
	return filepath.Walk(input_dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			return nil
		}

		rel, err := filepath.Rel(input_dir, path)
		if err != nil {
			return err
		}

		dst := filepath.Join(output_dir, rel)

		err = os.MkdirAll(filepath.Dir(dst), 0755)
		if err != nil {
			return err
		}

		if filepath.Ext(path) != ".sql" {
			return processGoFile(path, dst)
		}

		return processSQLFile(path, dst, dialect)
	})
}

func main() {
	args := os.Args[1:]
	dialect := dialectPostgres
	positional := make([]string, 0, 2)

	for _, arg := range args {
		if value, ok := strings.CutPrefix(arg, "--dialect="); ok {
			switch sqlDialect(value) {
			case dialectMySQL, dialectPostgres, dialectSQLite:
				dialect = sqlDialect(value)
			default:
				fmt.Fprintln(os.Stderr, "invalid dialect:", value)
				os.Exit(2)
			}
			continue
		}
		positional = append(positional, arg)
	}

	if len(positional) != 2 {
		fmt.Fprintln(os.Stderr, "usage: sql_minify <input> <output> [--dialect=mysql|postgres|sqlite]")
		os.Exit(1)
	}

	input_path := positional[0]
	output_path := positional[1]

	info, err := os.Stat(input_path)
	if err != nil {
		panic(err)
	}

	if info.IsDir() {
		err = processDirectory(input_path, output_path, dialect)
	} else {
		err = processSQLFile(input_path, output_path, dialect)
	}

	if err != nil {
		panic(err)
	}
}
