package main

import (
	"encoding/xml"
	"fmt"
	"io"
	"net/http"
	"os"
)

type supplementalData struct {
	WindowsZones windowsZones `xml:"windowsZones"`
}

type windowsZones struct {
	MapTimezones mapTimezones `xml:"mapTimezones"`
}

type mapTimezones struct {
	MapZones []mapZone `xml:"mapZone"`
}

type mapZone struct {
	Other     string `xml:"other,attr"`
	Territory string `xml:"territory,attr"`
	Type      string `xml:"type,attr"`
}

const url = "https://raw.githubusercontent.com/unicode-org/cldr/main/common/supplemental/windowsZones.xml"

const header = `// Code generated by gen_windows_to_iana. DO NOT EDIT.

package timezone

var windowsToIana = map[string]string{
`

func main() {
	response, err := http.Get(url)
	if err != nil {
		panic(err)
	}
	defer response.Body.Close()

	data, err := io.ReadAll(response.Body)
	if err != nil {
		panic(err)
	}

	var root supplementalData
	if err := xml.Unmarshal(data, &root); err != nil {
		panic(err)
	}

	file, err := os.Create("./miruzo/internal/adapter/timezone/iana_windows.go")
	if err != nil {
		panic(err)
	}
	defer file.Close()

	fmt.Fprint(file, header)

	for _, zone := range root.WindowsZones.MapTimezones.MapZones {
		if zone.Territory != "001" {
			continue
		}

		fmt.Fprintf(file, "\t%q: %q,\n", zone.Other, zone.Type)
	}

	fmt.Fprintln(file, "}")
}
