from typing import Protocol

from app.models.records import UserRecord


class UserRepository(Protocol):
	def get_singleton(self) -> UserRecord: ...

	def create_singleton_if_missing(self) -> UserRecord: ...

	def get_or_create_singleton(self) -> UserRecord: ...

	def try_increment_daily_love_used(self, *, limit: int) -> bool: ...

	def try_decrement_daily_love_used(self) -> bool: ...

	def reset_daily_love_used(self) -> None: ...
