-- Create FINITE_TIMESTAMP domain
CREATE DOMAIN FINITE_TIMESTAMP AS TIMESTAMP
CHECK (VALUE <> 'infinity' AND VALUE <> '-infinity');

-- Create settings table
CREATE TABLE settings(
	key VARCHAR PRIMARY KEY
		CONSTRAINT ck_settings_key
			NOT NULL
			CHECK (length(key) BETWEEN 2 AND 8),
	value VARCHAR NOT NULL
);

-- Create ingests table
CREATE TABLE ingests(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
		CONSTRAINT ck_ingests_id
			CHECK (id BETWEEN 1 AND 9007199254740991),
	process SMALLINT
		CONSTRAINT ck_ingests_process
			NOT NULL
			CHECK (process IN (0, 1))
			DEFAULT 0,
	visibility SMALLINT
		CONSTRAINT ck_ingests_visibility
			NOT NULL
			CHECK (visibility IN (0, 1))
			DEFAULT 0,
	relative_path VARCHAR(255)
		CONSTRAINT ck_ingests_relative_path
			NOT NULL
			CHECK (
				length(relative_path) >= 5
				AND relative_path NOT LIKE '/%'
				AND relative_path NOT LIKE '..%'
			),
	fingerprint VARCHAR(64)
		CONSTRAINT uq_ingests_fingerprint
			NOT NULL
			UNIQUE,
	ingested_at FINITE_TIMESTAMP NOT NULL,
	captured_at FINITE_TIMESTAMP NOT NULL CHECK (captured_at <= ingested_at),
	updated_at  FINITE_TIMESTAMP NOT NULL CHECK (updated_at >= ingested_at),
	executions JSONB
		CONSTRAINT ck_ingests_executions
			NOT NULL
			CHECK (jsonb_typeof(executions) = 'array' AND jsonb_array_length(executions) <= 5)
			DEFAULT '[]'::jsonb
);

-- Create images table
CREATE TABLE images(
	ingest_id BIGINT
		CONSTRAINT ck_images_ingest_id
			PRIMARY KEY
			REFERENCES ingests(id),
	ingested_at FINITE_TIMESTAMP NOT NULL,
	kind SMALLINT
		CONSTRAINT ck_images_kind
			NOT NULL
			CHECK (kind IN (0, 1, 2, 3))
			DEFAULT 0,
	original JSONB
		CONSTRAINT ck_images_original
			NOT NULL
			CHECK (jsonb_typeof(original) = 'object'),
	fallback JSONB
		CONSTRAINT ck_images_fallback
			CHECK (jsonb_typeof(fallback) = 'object'),
	variants JSONB
		CONSTRAINT ck_images_variants
			NOT NULL
			CHECK (jsonb_typeof(variants) = 'array')
);

-- Create stats table
CREATE TABLE stats(
	ingest_id BIGINT
		CONSTRAINT ck_stats_ingest_id
			PRIMARY KEY
			REFERENCES ingests(id)
			ON DELETE CASCADE,
	score SMALLINT NOT NULL,
	score_evaluated SMALLINT NOT NULL,
	score_evaluated_at FINITE_TIMESTAMP,
	first_loved_at FINITE_TIMESTAMP,
	last_loved_at FINITE_TIMESTAMP,
	hall_of_fame_at FINITE_TIMESTAMP,
	last_viewed_at FINITE_TIMESTAMP
		CONSTRAINT ck_stats_last_viewed_at
			CHECK (
				(view_count <> 0::BIGINT AND last_viewed_at IS NOT NULL)
				OR
				(view_count = 0::BIGINT AND last_viewed_at IS NULL)
			),
	view_count BIGINT
		NOT NULL
		CHECK (view_count >= 0)
		DEFAULT 0,
	view_milestone_count BIGINT
		NOT NULL
		CHECK (view_milestone_count >= 0 AND view_milestone_count <= view_count)
		DEFAULT 0,
	view_milestone_archived_at FINITE_TIMESTAMP
		CONSTRAINT ck_stats_view_milestone_archived_at
			CHECK (
				(view_milestone_count <> 0::BIGINT AND view_milestone_archived_at IS NOT NULL)
				OR
				(view_milestone_count = 0::BIGINT AND view_milestone_archived_at IS NULL)
			),
	CONSTRAINT ck_stats_loved_at_pair
		CHECK (
			(first_loved_at IS NULL AND last_loved_at IS NULL)
			OR
			(first_loved_at IS NOT NULL AND last_loved_at IS NOT NULL)
		),
	CONSTRAINT ck_stats_loved_at_order
		CHECK (first_loved_at IS NULL OR first_loved_at <= last_loved_at)
);

-- Create actions table
CREATE TABLE actions(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ingest_id BIGINT
		CONSTRAINT ck_actions_ingest_id
			NOT NULL
			REFERENCES ingests(id)
			ON DELETE CASCADE,
	kind SMALLINT
		CONSTRAINT ck_actions_kind
			NOT NULL
			CHECK (kind IN (0, 1, 11, 12, 13, 14, 15, 16))
			DEFAULT 0,
	occurred_at FINITE_TIMESTAMP NOT NULL
);

-- Create jobs table
CREATE TABLE jobs(
	name CHAR(16) PRIMARY KEY
		CONSTRAINT ck_jobs_name
			NOT NULL
			CHECK (length(name) >= 8),
	started_at FINITE_TIMESTAMP NOT NULL,
	finished_at FINITE_TIMESTAMP
);

-- Create users table
CREATE TABLE users(
	id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	daily_love_used SMALLINT
		CONSTRAINT ck_users_daily_love_used
			NOT NULL
			CHECK (daily_love_used BETWEEN 0 AND 100)
			DEFAULT 0
);
INSERT INTO users(id) VALUES(1);
